name: Clang format
on: [push, pull_request]
jobs:
  pre_job:
    name: Prerequisite checks
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          cancel_others: 'true'
  clang-format-pull:
    name: Clang Format
    needs: pre_job
    if: "github.event_name == 'pull_request' && needs.pre_job.outputs.should_skip != 'true'"
    runs-on: ubuntu-latest
    steps:
    - name: Define variables
      run: echo "Base_ref -> $BASE"
      env:
        BASE: if [[ ${{ github.event_name }} = 'pull_request' ]]; then 'origin/${{ github.base_ref }}'; else '${{ github.event.before }}'; fi 
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt-get install clang-format
    - name: Download git-clang-format
      run: wget https://raw.githubusercontent.com/llvm-mirror/clang/master/tools/clang-format/git-clang-format
    - name: Install git-clang-format
      run: sudo install -t /bin git-clang-format
    - name: Fetch ${{ env.BASE }}
      run: git fetch ${{ env.BASE }}
    - name: clang-format
      run: git clang-format ${{ env.BASE }}
    - name: diff
      run: git diff --exit-code
#  clang-format-push:
#    name: Clang Format
#    needs: pre_job
#    if: "github.event_name == 'push' && needs.pre_job.outputs.should_skip != 'true'"
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install clang-format
#      run: sudo apt-get install clang-format
#    - name: Download git-clang-format
#      run: wget https://raw.githubusercontent.com/llvm-mirror/clang/master/tools/clang-format/git-clang-format
#    - name: Install git-clang-format
#      run: sudo install -t /bin git-clang-format
#    - name: Fetch origin ${{ github.event.before }}
#      run: git fetch origin ${{ github.event.before }}
#    - name: clang-format
#      run: git clang-format ${{ github.event.before }}
#    - name: diff
#      run: git diff --exit-code
  
